cpo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^',include('generalzone.urls')),
    url(r'^userzone',include('userzone.urls')),
    url(r'^userzone/',include(('userzone.urls','userzone'),namespace='userzone')),
    url(r'^adminzone/', include(('adminzone.urls', 'adminzone'), namespace='adminzone')),
]

userzone/urls.py
from django.conf.urls import url
from . import views
urlpatterns=[
    url(r'^userhome',views.userhome ,name='userhome'),
    url(r'^discussion',views.discussion ,name='discussion'),
    url(r'^searchsolution',views.searchsolution ,name='searchsolution'),
    url(r'^complainlog',views.complainlog ,name='complainlog'),
    url(r'^changepassword',views.changepassword ,name='changepassword'),
    url(r'^logout',views.logout,name='logout'),
    url(r'^savecomplain',views.savecomplain,name='savecomplain'),
    url(r'^changepwd',views.changepwd,name='changepwd'),
    url(r'^postquestion',views.postquestion,name='postquestion'),
    url(r'^answer/(?P<qid>\d+)$',views.answer,name='answer'),
    url(r'^postanswer',views.postanswer,name='postanswer'),
    url(r'^viewanswer/(?P<qid>\d+)$',views.viewanswer,name='viewanswer'),
    url(r'^search',views.search,name='search'),
]

userzone/models.py
from django.db import models

# Create your models here.
class Complain(models.Model):
    name=models.CharField(max_length=50)
    gender=models.CharField(max_length=6)
    address=models.TextField()
    contactno=models.CharField(max_length=15)
    emailaddress=models.EmailField(max_length=50)
    subject=models.CharField(max_length=200)
    complaintext=models.TextField()
    complaindate=models.CharField(max_length=30)
class Question(models.Model):
    qid=models.AutoField(primary_key=True)
    questiontext=models.TextField()
    askedby=models.CharField(max_length=50)
    posteddate=models.CharField(max_length=30)
class Answer(models.Model):
    aid=models.AutoField(primary_key=True)
    answertext=models.TextField()
    answeredby=models.CharField(max_length=50)
    qid=models.IntegerField()
    answerddate=models.CharField(max_length=30)

userzone/views.py
from django.shortcuts import render,redirect,reverse
from generalzone.models import CustomerInfo,LoginInfo
import datetime
from . models import Complain,Question,Answer
from adminzone.models import Knowledgebase
from django.db.models import Q
# Create your views here.
def userhome(request):
    if request.session['userid']:
        return render(request,'userhome.html')
    else:
        return render(request,'login.html')
def discussion(request):
    if request.session['userid']:
        ques=Question.objects.all()
        return render(request,'discussion.html',{'ques':ques})
    else:
        return render(request,'login.html')
def complainlog(request):
    if request.session['userid']:
        return render(request,'complainlog.html')
    else:
        return render(request,'login.html')
def searchsolution(request):
    if request.session['userid']:
        return render(request,'searchsolution.html')
    else:
        return render(request,'login.html')
def changepassword(request):
    if request.session['userid']:
        return render(request,'changepassword.html')
    else:
        return render(request,'login.html')
def logout(request):
    if request.session['userid']:
        del request.session['userid']
        return redirect('login')
    else:
        return render(request,'logout.html')
def savecomplain(request):
    if request.session['userid']:
        emailaddress=request.session.get('userid')
        customer=CustomerInfo.objects.get(emailaddress=emailaddress)
        name=customer.name
        gender=customer.gender
        address=customer.address
        contactno=customer.contactno
        subject=request.POST['subject']
        complaintext=request.POST['complaintext']
        complaindate=datetime.datetime.now().strftime('%Y/%m/%d')
        com=Complain(name=name,gender=gender,address=address,contactno=contactno,emailaddress=emailaddress,subject=subject,complaintext=complaintext,complaindate=complaindate)
        com.save()
        return redirect('userzone:userhome')
    else:
        return render(request,'login.html')
def changepwd(request):
    if request.session['userid']:
        userid=request.session.get('userid')
        oldpassword=request.POST['oldpassword']
        newpassword=request.POST['newpassword']
        confirmpassword=request.POST['confirmpassword']
        if newpassword!=confirmpassword:
            return redirect('userzone:changepassword')
        else:
            user=LoginInfo.objects.get(userid=userid,password=oldpassword)
            if user is not None:
                li=LoginInfo(password=newpassword,userid=userid,usertype='customer')
                li.save()
                return render(request,'login.html')
            else:
                return redirect('userzone:changepassword')
    else:
        return render(request,'login.html')
def postquestion(request):
    if request.session['userid']:
        emailaddress=request.session.get('userid')
        customer=CustomerInfo.objects.get(emailaddress=emailaddress)
        askedby=customer.name
        questiontext=request.POST['questiontext']
        posteddate=datetime.datetime.now().strftime('%Y/%m/%d')
        q=Question(questiontext=questiontext,askedby=askedby,posteddate=posteddate)
        q.save()
        return redirect('userzone:discussion')
    else:
        return render(request,'login.html')
def answer(request,qid):
    if request.session['userid']:
        return render(request,'answer.html',{'qid':qid})
    else:
        return render(request,'login.html')
def postanswer(request):
    if request.session['userid']:
        emailaddress=request.session.get('userid')
        customer=CustomerInfo.objects.get(emailaddress=emailaddress)
        answeredby=customer.name
        qid=request.POST['qid']
        answertext=request.POST['answertext']
        answerddate=datetime.datetime.now().strftime('%Y/%m/%d')
        a=Answer(answertext=answertext,answeredby=answeredby,qid=qid,answerddate=answerddate)
        a.save()
        return redirect('userzone:discussion')
    else:
        return render(request,'login.html')
def viewanswer(request,qid):
    if request.session['userid']:
        ans=Answer.objects.filter(qid=qid)
        return render(request,'viewanswer.html',{'ans':ans})
    else:
        return render(request,'login.html')
def search(request):
    if request.session['userid']:
        searchtext=request.POST['searchtext']
        kw=Knowledgebase.objects.filter(Q(problemid=searchtext) | Q(problemtext=searchtext))
        return render(request,'searchsolution.html',{'kw':kw})
    else:
        return render(request,'login.html')

userzone/templates/answer.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>BLOGGING WEBSITE</title>

    <style>
#outer
{
min-height:950px;
width:1000px;
border:1px solid white;
margin:auto;
height:auto;
}
#header
{
height:150px;
width:1000px;
}#header
{
height:150px;
width:1000px;
}
#logo
{
height:150px;
width:150px;
background-color:cyan;
float:left;
}
#banner
{
height:150px;
width:850px;
background-color:teal;
float:right;
text-align:center;
line-height:150px;
}
#menu
{
width:1000px;
height:50px;
background-color:white;
margin-top:5px;
border:1px solid white;
}
#menu ul
{
 list-style-type:none;
}
#menu ul li
{
 display:inline;
}
#menu ul li a
{
 font-size:25px;
 padding:10px;
 text-decoration:none;
 color:black;
}
#menu ul li a:hover
{
 color:red;
}
#slider
{
width:1000px;
height:250px;
background-color:lightgrey;
margin-top:5px;

}
#parent
{
min-height:600px;
width:1000px;
margin-top:5px;
background-color:white;
height:auto;
}
#footer
{
width:1000px;
height:130px;
margin-top:5px
}
#lf
{
width:500px;
height:130px;
background-color:black;
color:white;
text-align:center;
float:right;
}
#rf
{
width:500px;
height:130px;
background-color:grey;
color:white;
text-align:center;
float:right;
}
</style>
</head>
<body bgcolor="blue" onload="moveslider()">
    <div id="outer">
        <div id="header">
            <div id="logo">
                <img src="{% static 'images/logo21.jpg' %}" height="150px" width="150px"/>
            </div>
            <div id="banner">CALL PROCESSING OPTIMIZATION</div>
        </div>
        <div id="menu">
            <ul>
                <li><a href="{% url 'userzone:userhome' %}"  >User Home</a></li>
                <li><a href="{% url 'userzone:discussion' %}"  >Discussion</a></li>
                <li><a href="{% url 'userzone:searchsolution' %}">Search solution</a></li>
                <li><a href="{% url 'userzone:complainlog' %}">Complain Log</a></li>
                <li><a href="{% url 'userzone:changepassword' %}">Change password</a></li>
                <li><a href="{% url 'userzone:logout' %}">Logout</a></li>
            </ul>


        </div>
        <div id="slider">
            <img id="slide" width="1000" height="250"/>
        </div>

        <div id="parent">
            <form action="{% url 'userzone:postanswer' %}" method="post">
                {% csrf_token %}
                <h2 style="text-align:center;color:blue;">
                    Discussion Forum
                </h2>
                <table border="1" style="margin:0 auto;width:50%;">
                    <tr>
                        <td>Enter Answer</td>
                        <td>
                            <textarea name="answertext" required style="height:100px;resize:none;"></textarea>
                        </td>
                     </tr>
                     <tr>
                        <td>
                        <input type="hidden" name="qid" value="{{qid}}" />
                        </td>
                        <td>
                            <input type="submit" value="Post"/>
                        </td>
                    </tr>

                </table>
            </form>
        </div>
        <div id="footer">
            <div id="lf"></div>
             <div id="rf"></div>
        </div>
        <div/>

</body>
</html>

userzone/templates/changepassword.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>BLOGGING WEBSITE</title>

    <style>
#outer
{
min-height:950px;
width:1000px;
border:1px solid white;
margin:auto;
height:auto;
}
#header
{
height:150px;
width:1000px;
}#header
{
height:150px;
width:1000px;
}
#logo
{
height:150px;
width:150px;
background-color:cyan;
float:left;
}
#banner
{
height:150px;
width:850px;
background-color:teal;
float:right;
text-align:center;
line-height:150px;
}
#menu
{
width:1000px;
height:50px;
background-color:white;
margin-top:5px;
border:1px solid white;
}
#menu ul
{
 list-style-type:none;
}
#menu ul li
{
 display:inline;
}
#menu ul li a
{
 font-size:25px;
 padding:10px;
 text-decoration:none;
 color:black;
}
#menu ul li a:hover
{
 color:red;
}
#slider
{
width:1000px;
height:250px;
background-color:lightgrey;
margin-top:5px;

}
#parent
{
min-height:600px;
width:1000px;
margin-top:5px;
background-color:white;
height:auto;
}
#footer
{
width:1000px;
height:130px;
margin-top:5px
}
#lf
{
width:500px;
height:130px;
background-color:black;
color:white;
text-align:center;
float:right;
}
#rf
{
width:500px;
height:130px;
background-color:grey;
color:white;
text-align:center;
float:right;
}
</style>
</head>
<body bgcolor="blue" onload="moveslider()">
    <div id="outer">
        <div id="header">
            <div id="logo">
                <img src="{% static 'images/logo21.jpg' %}" height="150px" width="150px"/>
            </div>
            <div id="banner">CALL PROCESSING OPTIMIZATION</div>
        </div>
        <div id="menu">
               <ul>
                <li><a href="{% url 'userzone:userhome' %}"  >User Home</a></li>
                <li><a href="{% url 'userzone:discussion' %}"  >Discussion</a></li>
                <li><a href="{% url 'userzone:searchsolution' %}">Search solution</a></li>
                <li><a href="{% url 'userzone:complainlog' %}">Complain Log</a></li>
                <li><a href="{% url 'userzone:changepassword' %}">Change password</a></li>
                <li><a href="#">Logout</a></li>
            </ul>



        </div>
        <div id="slider">
            <img id="slide" width="1000" height="250"/>
        </div>

        <div id="parent">
            <form action="{% url 'userzone:changepwd' %}" method="post">
                {% csrf_token %}
                <h2 style="color:blue;text-align:center">
                    Change your password
                </h2>
                <table border="1" style="color:blue; margin:0 auto; width:50%">
                    <tr>
                        <td>Enter old password</td>
                        <td>
                            <input type="password" name="oldpassword" required/>
                        </td>
                    </tr>
                    <tr>
                        <td>Enter new password</td>
                        <td>
                            <input type="password" name="newpassword" required/>
                        </td>
                    </tr>
                    <tr>
                        <td>Confirm password</td>
                        <td>
                            <input type="password" name="confirmpassword" required/>
                        </td>
                    </tr>
                    <tr>
                        <td>&nbsp</td>
                        <td>
                            <input type="submit" value="Change"/>
                        </td>
                    </tr>
                </table>
            </form>
        </div>
        <div id="footer">
            <div id="lf"></div>
             <div id="rf"></div>
        </div>
        <div/>

</body>
</html>

userzone/templates/complainlog.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>BLOGGING WEBSITE</title>

    <style>
#outer
{
min-height:950px;
width:1000px;
border:1px solid white;
margin:auto;
height:auto;
}
#header
{
height:150px;
width:1000px;
}#header
{
height:150px;
width:1000px;
}
#logo
{
height:150px;
width:150px;
background-color:cyan;
float:left;
}
#banner
{
height:150px;
width:850px;
background-color:teal;
float:right;
text-align:center;
line-height:150px;
}
#menu
{
width:1000px;
height:50px;
background-color:white;
margin-top:5px;
border:1px solid white;
}
#menu ul
{
 list-style-type:none;
}
#menu ul li
{
 display:inline;
}
#menu ul li a
{
 font-size:25px;
 padding:10px;
 text-decoration:none;
 color:black;
}
#menu ul li a:hover
{
 color:red;
}
#slider
{
width:1000px;
height:250px;
background-color:lightgrey;
margin-top:5px;

}
#parent
{
min-height:600px;
width:1000px;
margin-top:5px;
background-color:white;
height:auto;
}
#footer
{
width:1000px;
height:130px;
margin-top:5px
}
#lf
{
width:500px;
height:130px;
background-color:black;
color:white;
text-align:center;
float:right;
}
#rf
{
width:500px;
height:130px;
background-color:grey;
color:white;
text-align:center;
float:right;
}
</style>
</head>
<body bgcolor="blue" onload="moveslider()">
    <div id="outer">
        <div id="header">
            <div id="logo">
                <img src="{% static 'images/logo21.jpg' %}" height="150px" width="150px"/>
            </div>
            <div id="banner">CALL PROCESSING OPTIMIZATION</div>
        </div>
        <div id="menu">
               <ul>
                <li><a href="{% url 'userzone:userhome' %}"  >User Home</a></li>
                <li><a href="{% url 'userzone:discussion' %}"  >Discussion</a></li>
                <li><a href="{% url 'userzone:searchsolution' %}">Search solution</a></li>
                <li><a href="{% url 'userzone:complainlog' %}">Complain Log</a></li>
                <li><a href="{% url 'userzone:changepassword' %}">Change password</a></li>
                <li><a href="#">Logout</a></li>
            </ul>



        </div>
        <div id="slider">
            <img id="slide" width="1000" height="250"/>
        </div>

        <div id="parent">
            <form action="{% url 'userzone:savecomplain' %}" method="post">
                {% csrf_token %}
                <h2 style="color:blue;text-align:center;">
                    Complain Logging System
                </h2>
                <table border="1" style="width:80%;margin:0 auto;">
                    <tr>
                        <td>Enter Subject</td>
                        <td>
                            <input type="text" name="subject" required/>
                        </td>
                    </tr>
                    <tr>
                        <td>Enter Complain</td>
                        <td>
                            <textarea name="complaintext" required style="height:150px;resize:none;"></textarea>
                        </td>
                    </tr>
                    <tr>
                        <td>&nbsp</td>
                        <td>
                            <input type="submit" value="Submit"/>
                        </td>
                    </tr>
                </table>
            </form>
        </div>
        <div id="footer">
            <div id="lf"></div>
             <div id="rf"></div>
        </div>
        <div/>

</body>
</html>

userzone/templates/discussion.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>BLOGGING WEBSITE</title>

    <style>
#outer
{
min-height:950px;
width:1000px;
border:1px solid white;
margin:auto;
height:auto;
}
#header
{
height:150px;
width:1000px;
}#header
{
height:150px;
width:1000px;
}
#logo
{
height:150px;
width:150px;
background-color:cyan;
float:left;
}
#banner
{
height:150px;
width:850px;
background-color:teal;
float:right;
text-align:center;
line-height:150px;
}
#menu
{
width:1000px;
height:50px;
background-color:white;
margin-top:5px;
border:1px solid white;
}
#menu ul
{
 list-style-type:none;
}
#menu ul li
{
 display:inline;
}
#menu ul li a
{
 font-size:25px;
 padding:10px;
 text-decoration:none;
 color:black;
}
#menu ul li a:hover
{
 color:red;
}
#slider
{
width:1000px;
height:250px;
background-color:lightgrey;
margin-top:5px;

}
#parent
{
min-height:600px;
width:1000px;
margin-top:5px;
background-color:white;
height:auto;
}
#footer
{
width:1000px;
height:130px;
margin-top:5px
}
#lf
{
width:500px;
height:130px;
background-color:black;
color:white;
text-align:center;
float:right;
}
#rf
{
width:500px;
height:130px;
background-color:grey;
color:white;
text-align:center;
float:right;
}
</style>
</head>
<body bgcolor="blue" onload="moveslider()">
    <div id="outer">
        <div id="header">
            <div id="logo">
                <img src="{% static 'images/logo21.jpg' %}" height="150px" width="150px"/>
            </div>
            <div id="banner">CALL PROCESSING OPTIMIZATION</div>
        </div>
        <div id="menu">
               <ul>
                <li><a href="{% url 'userzone:userhome' %}"  >User Home</a></li>
                <li><a href="{% url 'userzone:discussion' %}"  >Discussion</a></li>
                <li><a href="{% url 'userzone:searchsolution' %}">Search solution</a></li>
                <li><a href="{% url 'userzone:complainlog' %}">Complain Log</a></li>
                <li><a href="{% url 'userzone:changepassword' %}">Change password</a></li>
                <li><a href="#">Logout</a></li>
            </ul>



        </div>
        <div id="slider">
            <img id="slide" width="1000" height="250"/>
        </div>

        <div id="parent">
            <form action="{% url 'userzone:postquestion' %}" method="post">
                {% csrf_token %}
                <h2 style="text-align:center;color:blue;">
                    Discussion Forum
                </h2>
                <table border="1" style="margin:0 auto;width:50%;">
                    <tr>
                        <td>Enter Question</td>
                        <td>
                            <textarea name="questiontext" required style="height:100px;resize:none;"></textarea>
                        </td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>
                            <input type="submit" value="Post"/>
                        </td>
                    </tr>

                </table>
            </form>
            <table border="1" style="width:80%; margin:0 auto;">
                <tr>
                    <th>Question</th>
                    <th>Asked By</th>
                    <th>Posted Date</th>
                    <th>Post Answer</th>
                    <th>View Answer</th>
                </tr>
                {% for q in ques %}
                <tr>
                    <td>{{q.questiontext}}</td>
                    <td>{{q.askedby}}</td>
                    <td>{{q.posteddate}}</td>
                    <td><a href="{% url 'userzone:answer' q.qid %}">Post</a></td>
                    <td><a href="{% url 'userzone:viewanswer' q.qid %}">View</a></td>
                </tr>
                {% endfor %}

            </table>
        </div>
        <div id="footer">
            <div id="lf"></div>
             <div id="rf"></div>
        </div>
        <div/>

</body>
</html>

userzone/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

userzone/templates/searchsolution.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>BLOGGING WEBSITE</title>

    <style>
#outer
{
min-height:950px;
width:1000px;
border:1px solid white;
margin:auto;
height:auto;
}
#header
{
height:150px;
width:1000px;
}#header
{
height:150px;
width:1000px;
}
#logo
{
height:150px;
width:150px;
background-color:cyan;
float:left;
}
#banner
{
height:150px;
width:850px;
background-color:teal;
float:right;
text-align:center;
line-height:150px;
}
#menu
{
width:1000px;
height:50px;
background-color:white;
margin-top:5px;
border:1px solid white;
}
#menu ul
{
 list-style-type:none;
}
#menu ul li
{
 display:inline;
}
#menu ul li a
{
 font-size:25px;
 padding:10px;
 text-decoration:none;
 color:black;
}
#menu ul li a:hover
{
 color:red;
}
#slider
{
width:1000px;
height:250px;
background-color:lightgrey;
margin-top:5px;

}
#parent
{
min-height:600px;
width:1000px;
margin-top:5px;
background-color:white;
height:auto;
}
#footer
{
width:1000px;
height:130px;
margin-top:5px
}
#lf
{
width:500px;
height:130px;
background-color:black;
color:white;
text-align:center;
float:right;
}
#rf
{
width:500px;
height:130px;
background-color:grey;
color:white;
text-align:center;
float:right;
}
</style>
</head>
<body bgcolor="blue" onload="moveslider()">
    <div id="outer">
        <div id="header">
            <div id="logo">
                <img src="{% static 'images/logo21.jpg' %}" height="150px" width="150px"/>
            </div>
            <div id="banner">CALL PROCESSING OPTIMIZATION</div>
        </div>
        <div id="menu">
               <ul>
                <li><a href="{% url 'userzone:userhome' %}"  >User Home</a></li>
                <li><a href="{% url 'userzone:discussion' %}"  >Discussion</a></li>
                <li><a href="{% url 'userzone:searchsolution' %}">Search solution</a></li>
                <li><a href="{% url 'userzone:complainlog' %}">Complain Log</a></li>
                <li><a href="{% url 'userzone:changepassword' %}">Change password</a></li>
                <li><a href="#">Logout</a></li>
            </ul>



        </div>
        <div id="slider">
            <img id="slide" width="1000" height="250"/>
        </div>

        <div id="parent">
            <form action="{% url 'userzone:search' %}" method="post">
                {% csrf_token %}
                <h2 style="color:blue;text-align:center;">
                    Search Solution
                </h2>
                <table border="1" style="width:50%;margin:0 auto;">
                    <tr>
                        <td>Enter problem id or problem text</td>
                        <td>
                            <textarea name="searchtext" required style="height:100px;resize:none;"></textarea>
                        </td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>
                            <input type="submit" value="Search"/>
                        </td>
                    </tr>

                </table>
            </form>
            <ul>
            {% for k in kw %}
                <li style="color:red;">{{k.problemtext}}</li>
                <li style="color:green;">{{k.solutiontext}}</li>
            {% endfor %}
            </ul>
        </div>
        <div id="footer">
            <div id="lf"></div>
             <div id="rf"></div>
        </div>
        <div/>

</body>
</html>

userzone/templates/userhome.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>BLOGGING WEBSITE</title>

    <style>
#outer
{
min-height:950px;
width:1000px;
border:1px solid white;
margin:auto;
height:auto;
}
#header
{
height:150px;
width:1000px;
}#header
{
height:150px;
width:1000px;
}
#logo
{
height:150px;
width:150px;
background-color:cyan;
float:left;
}
#banner
{
height:150px;
width:850px;
background-color:teal;
float:right;
text-align:center;
line-height:150px;
}
#menu
{
width:1000px;
height:50px;
background-color:white;
margin-top:5px;
border:1px solid white;
}
#menu ul
{
 list-style-type:none;
}
#menu ul li
{
 display:inline;
}
#menu ul li a
{
 font-size:25px;
 padding:10px;
 text-decoration:none;
 color:black;
}
#menu ul li a:hover
{
 color:red;
}
#slider
{
width:1000px;
height:250px;
background-color:lightgrey;
margin-top:5px;

}
#parent
{
min-height:600px;
width:1000px;
margin-top:5px;
background-color:white;
height:auto;
}
#footer
{
width:1000px;
height:130px;
margin-top:5px
}
#lf
{
width:500px;
height:130px;
background-color:black;
color:white;
text-align:center;
float:right;
}
#rf
{
width:500px;
height:130px;
background-color:grey;
color:white;
text-align:center;
float:right;
}
</style>
</head>
<body bgcolor="blue" onload="moveslider()">
    <div id="outer">
        <div id="header">
            <div id="logo">
                <img src="{% static 'images/logo21.jpg' %}" height="150px" width="150px"/>
            </div>
            <div id="banner">CALL PROCESSING OPTIMIZATION</div>
        </div>
        <div id="menu">
            <ul>
                <li><a href="{% url 'userzone:userhome' %}"  >User Home</a></li>
                <li><a href="{% url 'userzone:discussion' %}"  >Discussion</a></li>
                <li><a href="{% url 'userzone:searchsolution' %}">Search solution</a></li>
                <li><a href="{% url 'userzone:complainlog' %}">Complain Log</a></li>
                <li><a href="{% url 'userzone:changepassword' %}">Change password</a></li>
                <li><a href="{% url 'userzone:logout' %}">Logout</a></li>
            </ul>


        </div>
        <div id="slider">
            <img id="slide" width="1000" height="250"/>
        </div>

        <div id="parent">

        </div>
        <div id="footer">
            <div id="lf"></div>
             <div id="rf"></div>
        </div>
        <div/>

</body>
</html>

userzone/templates/viewanswer.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>BLOGGING WEBSITE</title>

    <style>
#outer
{
min-height:950px;
width:1000px;
border:1px solid white;
margin:auto;
height:auto;
}
#header
{
height:150px;
width:1000px;
}#header
{
height:150px;
width:1000px;
}
#logo
{
height:150px;
width:150px;
background-color:cyan;
float:left;
}
#banner
{
height:150px;
width:850px;
background-color:teal;
float:right;
text-align:center;
line-height:150px;
}
#menu
{
width:1000px;
height:50px;
background-color:white;
margin-top:5px;
border:1px solid white;
}
#menu ul
{
 list-style-type:none;
}
#menu ul li
{
 display:inline;
}
#menu ul li a
{
 font-size:25px;
 padding:10px;
 text-decoration:none;
 color:black;
}
#menu ul li a:hover
{
 color:red;
}
#slider
{
width:1000px;
height:250px;
background-color:lightgrey;
margin-top:5px;

}
#parent
{
min-height:600px;
width:1000px;
margin-top:5px;
background-color:white;
height:auto;
}
#footer
{
width:1000px;
height:130px;
margin-top:5px
}
#lf
{
width:500px;
height:130px;
background-color:black;
color:white;
text-align:center;
float:right;
}
#rf
{
width:500px;
height:130px;
background-color:grey;
color:white;
text-align:center;
float:right;
}
</style>
</head>
<body bgcolor="blue" onload="moveslider()">
    <div id="outer">
        <div id="header">
            <div id="logo">
                <img src="{% static 'images/logo21.jpg' %}" height="150px" width="150px"/>
            </div>
            <div id="banner">CALL PROCESSING OPTIMIZATION</div>
        </div>
        <div id="menu">
            <ul>
                <li><a href="{% url 'userzone:userhome' %}"  >User Home</a></li>
                <li><a href="{% url 'userzone:discussion' %}"  >Discussion</a></li>
                <li><a href="{% url 'userzone:searchsolution' %}">Search solution</a></li>
                <li><a href="{% url 'userzone:complainlog' %}">Complain Log</a></li>
                <li><a href="{% url 'userzone:changepassword' %}">Change password</a></li>
                <li><a href="{% url 'userzone:logout' %}">Logout</a></li>
            </ul>


        </div>
        <div id="slider">
            <img id="slide" width="1000" height="250"/>
        </div>

        <div id="parent">
            <h2 style="text-align:center;color:blue;">
                Discussion Forum
            </h2>
            <table border="1" style="width:80%;margin:0 auto;">
                <tr>
                    <th>Answer</th>
                    <th>Answered By</th>
                    <th>Answered Date</th>
                </tr>
                {% for a in ans %}
                    <tr>
                        <td>{{a.answertext}}</td>
                        <td>{{a.answeredby}}</td>
                        <td>{{a.answerddate}}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        <div id="footer">
            <div id="lf"></div>
             <div id="rf"></div>
        </div>
        <div/>

</body>
</html>