adminzone/urls.py
from django.conf.urls import url
from . import views
urlpatterns=[
   url(r'^adminhome',views.adminhome,name='adminhome'),
   url(r'^enquiries',views.enquiries,name='enquiries'),
   url(r'^complains',views.complains,name='complains'),
   url(r'^customerinfo',views.customerinfo,name='customerinfo'),
   url(r'^knowledgebase',views.knowledgebase,name='knowledgebase'),
   url(r'^logout',views.logout,name='logout'),
   url(r'^addnotification',views.addnotification,name='addnotification'),
   url(r'^deletenotification/(?P<id>\d+)$',views.deletenotification,name='deletenotification'),
   url(r'^deleteenquiries/(?P<id>\d+)$', views.deleteenquiries, name='deleteenquiries'),
   url(r'^deletecomplains/(?P<id>\d+)$', views.deletecomplains, name='deletecomplains'),
   url(r'^deletecustomerinfo/(?P<emailaddress>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$',views.deletecustomerinfo,name='deletecustomerinfo'),
   url(r'^saveknowledgebase',views.saveknowledgebase,name='saveknowledgebase'),
]

cpo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^',include('generalzone.urls')),
    url(r'^userzone',include('userzone.urls')),
    url(r'^userzone/',include(('userzone.urls','userzone'),namespace='userzone')),
    url(r'^adminzone/', include(('adminzone.urls', 'adminzone'), namespace='adminzone')),
]

adminzone/models.py
from django.db import models

# Create your models here.
class Notification(models.Model):
    notificationtext=models.TextField()
    posteddate=models.CharField(max_length=30)
class Knowledgebase(models.Model):
    problemid=models.CharField(max_length=20)
    problemtext=models.TextField()
    solutiontext=models.TextField()
    posteddate=models.CharField(max_length=30)

adminzone/views.py
from django.shortcuts import render,redirect
from generalzone.models import Enquiry,CustomerInfo,LoginInfo
from userzone.models import Complain
from . models import Knowledgebase,Notification
import datetime
# Create your views here.
def adminhome(request):
    if request.session['adminid']:
        noti=Notification.objects.all()
        return render(request,'adminhome.html',{'noti':noti})
    else:
        return render(request,'login.html')
def enquiries(request):
    if request.session['adminid']:
        enq=Enquiry.objects.all()
        return render(request,'enquiries.html',{'enq':enq})
    else:
        return render(request,'login.html')

def complains(request):
    if request.session['adminid']:
        comp=Complain.objects.all()
        return render(request, 'complains.html',{'comp':comp})
    else:
        return render(request, 'login.html')

def customerinfo(request):
    if request.session['adminid']:
        cust=CustomerInfo.objects.all()
        return render(request, 'customerinfo.html',{'cust':cust})
    else:
        return render(request, 'login.html')
def knowledgebase(request):
    if request.session['adminid']:
        return render(request,'knowledgebase.html')
    else:
        return render(request,'login.html')
def logout(request):
    del request.session['adminid']
    return render(request,'login.html')
def addnotification(request):
    if request.session['adminid']:
        notificationtext=request.POST['notificationtext']
        posteddate=datetime.datetime.now().strftime('%Y/%m/%d')
        n=Notification(notificationtext=notificationtext,posteddate=posteddate)
        n.save()
        return redirect('adminzone:adminhome')
    else:
        return render(request,'login.html')
def deletenotification(request,id):
    if request.session['adminid']:
        n=Notification.objects.get(id=id)
        n.delete()
        return redirect('adminzone:adminhome')
    else:
        return render(request,'login.html')
def deleteenquiries(request,id):
    if request.session['adminid']:
        e=Enquiry.objects.get(id=id)
        e.delete()
        return redirect('adminzone:enquiries')
    else:
        return render(request,'login.html')
def deletecomplains(request,id):
    if request.session['adminid']:
        c=Complain.objects.get(id=id)
        c.delete()
        return redirect('adminzone:complains')
    else:
        return render(request,'login.html')
def deletecustomerinfo(request,emailaddress):
    if request.session['adminid']:
        c=CustomerInfo.objects.get(emailaddress=emailaddress)
        l=LoginInfo.objects.get(userid=emailaddress)
        c.delete()
        l.delete()
        return redirect('adminzone:customerinfo')
    else:
        return render(request,'login.html')
def saveknowledgebase(request):
    if request.session['adminid']:
        problemid=request.POST['problemid']
        problemtext=request.POST['problemtext']
        solutiontext=request.POST['solutiontext']
        posteddate=datetime.datetime.now().strftime('%Y/%m/%d')
        kw=Knowledgebase(problemid=problemid,problemtext=problemtext,solutiontext=solutiontext,posteddate=posteddate)
        kw.save()
        return redirect('adminzone:knowledgebase')
    else:
        return render(request,'login.html')

adminzone/templates/adminhome.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>BLOGGING WEBSITE</title>

    <style>
#outer
{
min-height:950px;
width:1000px;
border:1px solid white;
margin:auto;
height:auto;
}
#header
{
height:150px;
width:1000px;
}#header
{
height:150px;
width:1000px;
}
#logo
{
height:150px;
width:150px;
background-color:cyan;
float:left;
}
#banner
{
height:150px;
width:850px;
background-color:teal;
float:right;
text-align:center;
line-height:150px;
}
#menu
{
width:1000px;
height:50px;
background-color:white;
margin-top:5px;
border:1px solid white;
}
#menu ul
{
 list-style-type:none;
}
#menu ul li
{
 display:inline;
}
#menu ul li a
{
 font-size:25px;
 padding:10px;
 text-decoration:none;
 color:black;
}
#menu ul li a:hover
{
 color:red;
}
#slider
{
width:1000px;
height:250px;
background-color:lightgrey;
margin-top:5px;

}
#parent
{
min-height:600px;
width:1000px;
margin-top:5px;
background-color:white;
height:auto;
}
#footer
{
width:1000px;
height:130px;
margin-top:5px
}
#lf
{
width:500px;
height:130px;
background-color:black;
color:white;
text-align:center;
float:right;
}
#rf
{
width:500px;
height:130px;
background-color:grey;
color:white;
text-align:center;
float:right;
}
</style>
<script>
    var images=["admin1.jpg" , "admin2"];
   var i=0;
   baseUrl="{% static 'images/'%}";
   function moveslider()
   {
     if (i==2)
     {
      i=0;
     }
     document.getElementById("slide").src=baseUrl+images[i];
     i++;
     window.setTimeout("moveslider()",1000);
   }
</script>
</head>
<body bgcolor="blue" onload="moveslider()">
    <div id="outer">
        <div id="header">
            <div id="logo">
                <img src="{% static 'images/blogparent.jpg' %}" height="150px" width="150px"/>
            </div>
            <div id="banner">BLOGGING WEBSITE</div>
        </div>
        <div id="menu">
            <ul>
                <li><a href="{% url 'adminzone:adminhome' %}">Admin Home</a></li>
                <li><a href="{% url 'adminzone:enquiries' %}">Enquiries</a></li>
                <li><a href="{% url 'adminzone:complains' %}">Complains</a></li>
                <li><a href="{% url 'adminzone:customerinfo' %}">Customer Info</a></li>
                <li><a href="{% url 'adminzone:knowledgebase' %}">Knowledgebase</a></li>
                <li><a href="{% url 'adminzone:logout' %}">Logout</a></li>
            </ul>


        </div>
        <div id="slider">
            <img id="slide" width="1000" height="250"/>
        </div>

        <div id="parent">
            <form action="{% url 'adminzone:addnotification' %}" method="post">
                {% csrf_token %}
                <h2 style="text-align:center;color:blue;">
                    Add Notification
                </h2>
                <table border="1" style="margin:0 auto; width:50%">
                    <tr>
                        <td>Enter Notification</td>
                        <td>
                            <textarea name="notificationtext" required style="height:100px; resize:none;"></textarea>
                        </td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>
                            <input type="submit" value="Add"/>
                        </td>
                    </tr>

                </table>
            </form>
            <table border="1" style="width:80%;margin:0 auto;">
              <tr>
                  <th>Id</th>
                  <th>Notification</th>
                  <th>Posted Date</th>
                  <th>Delete</th>
              </tr>
                {% for n in noti %}
                <tr>
                    <td>{{n.id}}</td>
                    <td>{{n.notificationtext}}</td>
                    <td>{{n.posteddate}}</td>
                    <td>
                        <a href="{% url 'adminzone:deletenotification' n.id %}">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <div id="footer">
            <div id="lf"></div>
             <div id="rf"></div>
        </div>
        <div/>

</body>
</html>

adminzone/templates/complains.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>BLOGGING WEBSITE</title>

    <style>
#outer
{
min-height:950px;
width:1000px;
border:1px solid white;
margin:auto;
height:auto;
}
#header
{
height:150px;
width:1000px;
}#header
{
height:150px;
width:1000px;
}
#logo
{
height:150px;
width:150px;
background-color:cyan;
float:left;
}
#banner
{
height:150px;
width:850px;
background-color:teal;
float:right;
text-align:center;
line-height:150px;
}
#menu
{
width:1000px;
height:50px;
background-color:white;
margin-top:5px;
border:1px solid white;
}
#menu ul
{
 list-style-type:none;
}
#menu ul li
{
 display:inline;
}
#menu ul li a
{
 font-size:25px;
 padding:10px;
 text-decoration:none;
 color:black;
}
#menu ul li a:hover
{
 color:red;
}
#slider
{
width:1000px;
height:250px;
background-color:lightgrey;
margin-top:5px;

}
#parent
{
min-height:600px;
width:1000px;
margin-top:5px;
background-color:white;
height:auto;
}
#footer
{
width:1000px;
height:130px;
margin-top:5px
}
#lf
{
width:500px;
height:130px;
background-color:black;
color:white;
text-align:center;
float:right;
}
#rf
{
width:500px;
height:130px;
background-color:grey;
color:white;
text-align:center;
float:right;
}
</style>
<script>
    var images=["admin1.jpg" , "admin2","complain1.jpg" ,"complain2.jpg" ,"complain3.jpg"];
   var i=0;
   baseUrl="{% static 'images/'%}";
   function moveslider()
   {
     if (i==5)
     {
      i=0;
     }
     document.getElementById("slide").src=baseUrl+images[i];
     i++;
     window.setTimeout("moveslider()",1000);
   }
</script>
</head>
<body bgcolor="blue" onload="moveslider()">
    <div id="outer">
        <div id="header">
            <div id="logo">
                <img src="{% static 'images/blogparent.jpg' %}" height="150px" width="150px"/>
            </div>
            <div id="banner">BLOGGING WEBSITE</div>
        </div>
        <div id="menu">
            <ul>
                <li><a href="{% url 'adminzone:adminhome' %}">Admin Home</a></li>
                <li><a href="{% url 'adminzone:enquiries' %}">Enquiries</a></li>
                <li><a href="{% url 'adminzone:complains' %}">Complains</a></li>
                <li><a href="{% url 'adminzone:customerinfo' %}">Customer Info</a></li>
                <li><a href="{% url 'adminzone:knowledgebase' %}">Knowledgebase</a></li>
                <li><a href="{% url 'adminzone:logout' %}">Logout</a></li>
            </ul>


        </div>
        <div id="slider">
            <img id="slide" width="1000" height="250"/>
        </div>

        <div id="parent">
            <h2 style="text-align:center;color:blue;">
                View All Complains
            </h2>
            <table border=1 style="margin:0 auto;width:90%;">
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Gender</th>
                    <th>Address</th>
                    <th>Contact No</th>
                    <th>Email Address</th>
                    <th>Subject</th>
                    <th>Complain</th>
                    <th>Date</th>
                    <th>Delete</th>
                </tr>
                {% for c in comp %}
                <tr>
                    <td>{{c.id}}</td>
                    <td>{{c.name}}</td>
                    <td>{{c.gender}}</td>
                    <td>{{c.address}}</td>
                    <td>{{c.contactno}}</td>
                    <td>{{c.emailaddress}}</td>
                    <td>{{c.subject}}</td>
                    <td>{{c.complaintext}}</td>
                    <td>{{c.complaindate}}</td>
                    <td>
                        <a href="{% url 'adminzone:deletecomplains' c.id %}">Delete</a>
                    </td>
                </tr>
                {% endfor %}

            </table>
        </div>
        <div id="footer">
            <div id="lf"></div>
             <div id="rf"></div>
        </div>
        <div/>

</body>
</html>

adminzone/templates/customerinfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>BLOGGING WEBSITE</title>

    <style>
#outer
{
min-height:950px;
width:1000px;
border:1px solid white;
margin:auto;
height:auto;
}
#header
{
height:150px;
width:1000px;
}#header
{
height:150px;
width:1000px;
}
#logo
{
height:150px;
width:150px;
background-color:cyan;
float:left;
}
#banner
{
height:150px;
width:850px;
background-color:teal;
float:right;
text-align:center;
line-height:150px;
}
#menu
{
width:1000px;
height:50px;
background-color:white;
margin-top:5px;
border:1px solid white;
}
#menu ul
{
 list-style-type:none;
}
#menu ul li
{
 display:inline;
}
#menu ul li a
{
 font-size:25px;
 padding:10px;
 text-decoration:none;
 color:black;
}
#menu ul li a:hover
{
 color:red;
}
#slider
{
width:1000px;
height:250px;
background-color:lightgrey;
margin-top:5px;

}
#parent
{
min-height:600px;
width:1000px;
margin-top:5px;
background-color:white;
height:auto;
}
#footer
{
width:1000px;
height:130px;
margin-top:5px
}
#lf
{
width:500px;
height:130px;
background-color:black;
color:white;
text-align:center;
float:right;
}
#rf
{
width:500px;
height:130px;
background-color:grey;
color:white;
text-align:center;
float:right;
}
</style>
<script>
    var images=["admin1.jpg" , "admin2","customer1.jpg","customer2.jpg","customer3.jpg"];
   var i=0;
   baseUrl="{% static 'images/'%}";
   function moveslider()
   {
     if (i==5)
     {
      i=0;
     }
     document.getElementById("slide").src=baseUrl+images[i];
     i++;
     window.setTimeout("moveslider()",1000);
   }
</script>
</head>
<body bgcolor="blue" onload="moveslider()">
    <div id="outer">
        <div id="header">
            <div id="logo">
                <img src="{% static 'images/blogparent.jpg' %}" height="150px" width="150px"/>
            </div>
            <div id="banner">BLOGGING WEBSITE</div>
        </div>
        <div id="menu">
            <ul>
                <li><a href="{% url 'adminzone:adminhome' %}">Admin Home</a></li>
                <li><a href="{% url 'adminzone:enquiries' %}">Enquiries</a></li>
                <li><a href="{% url 'adminzone:complains' %}">Complains</a></li>
                <li><a href="{% url 'adminzone:customerinfo' %}">Customer Info</a></li>
                <li><a href="{% url 'adminzone:knowledgebase' %}">Knowledgebase</a></li>
                <li><a href="{% url 'adminzone:logout' %}">Logout</a></li>
            </ul>


        </div>
        <div id="slider">
            <img id="slide" width="1000" height="250"/>
        </div>

        <div id="parent">
            <h2 style="color:blue;text-align:center;">
                View All Customers
            </h2>
            <table border="1" style="margin:0 auto;width:90%;">
                <tr>
                    <th>Name</th>
                    <th>Gender</th>
                    <th>Address</th>
                    <th>Nationality</th>
                    <th>Contact No</th>
                    <th>Email Address</th>
                    <th>Connect Date</th>
                    <th>Delete</th>
                </tr>
                {% for c in cust %}
                <tr>
                    <td>{{c.name}}</td>
                    <td>{{c.gender}}</td>
                    <td>{{c.address}}</td>
                    <td>{{c.nationality}}</td>
                    <td>{{c.contactno}}</td>
                    <td>{{c.emailaddress}}</td>
                    <td>{{c.connectdate}}</td>
                    <td>
                        <a href="{% url 'adminzone:deletecustomerinfo' emailaddress=c.emailaddress %}">Delete</a>
                    </td>
                </tr>
                {% endfor %}

            </table>
        </div>
        <div id="footer">
            <div id="lf"></div>
             <div id="rf"></div>
        </div>
        <div/>

</body>
</html>

adminzone/templates/enquiries.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>BLOGGING WEBSITE</title>

    <style>
#outer
{
min-height:950px;
width:1000px;
border:1px solid white;
margin:auto;
height:auto;
}
#header
{
height:150px;
width:1000px;
}#header
{
height:150px;
width:1000px;
}
#logo
{
height:150px;
width:150px;
background-color:cyan;
float:left;
}
#banner
{
height:150px;
width:850px;
background-color:teal;
float:right;
text-align:center;
line-height:150px;
}
#menu
{
width:1000px;
height:50px;
background-color:white;
margin-top:5px;
border:1px solid white;
}
#menu ul
{
 list-style-type:none;
}
#menu ul li
{
 display:inline;
}
#menu ul li a
{
 font-size:25px;
 padding:10px;
 text-decoration:none;
 color:black;
}
#menu ul li a:hover
{
 color:red;
}
#slider
{
width:1000px;
height:250px;
background-color:lightgrey;
margin-top:5px;

}
#parent
{
min-height:600px;
width:1000px;
margin-top:5px;
background-color:white;
height:auto;
}
#footer
{
width:1000px;
height:130px;
margin-top:5px
}
#lf
{
width:500px;
height:130px;
background-color:black;
color:white;
text-align:center;
float:right;
}
#rf
{
width:500px;
height:130px;
background-color:grey;
color:white;
text-align:center;
float:right;
}
</style>
<script>
    var images=["admin1.jpg" , "admin2","enquiry1.jpg" ,"enquiry2.jpg" ,"enquiry3.jpg"];
   var i=0;
   baseUrl="{% static 'images/'%}";
   function moveslider()
   {
     if (i==5)
     {
      i=0;
     }
     document.getElementById("slide").src=baseUrl+images[i];
     i++;
     window.setTimeout("moveslider()",1000);
   }
</script>
</head>
<body bgcolor="blue" onload="moveslider()">
    <div id="outer">
        <div id="header">
            <div id="logo">
                <img src="{% static 'images/blogparent.jpg' %}" height="150px" width="150px"/>
            </div>
            <div id="banner">BLOGGING WEBSITE</div>
        </div>
        <div id="menu">
            <ul>
                <li><a href="{% url 'adminzone:adminhome' %}">Admin Home</a></li>
                <li><a href="{% url 'adminzone:enquiries' %}">Enquiries</a></li>
                <li><a href="{% url 'adminzone:complains' %}">Complains</a></li>
                <li><a href="{% url 'adminzone:customerinfo' %}">Customer Info</a></li>
                <li><a href="{% url 'adminzone:knowledgebase' %}">Knowledgebase</a></li>
                <li><a href="{% url 'adminzone:logout' %}">Logout</a></li>
            </ul>


        </div>
        <div id="slider">
            <img id="slide" width="1000" height="250"/>
        </div>

        <div id="parent">
            <h2 style="text-align:center;color:blue;">
                View All Enquiries
            </h2>
            <table border="1" style="margin:0 auto;width:90%;">
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Gender</th>
                    <th>Address</th>
                    <th>Contact No</th>
                    <th>Email address</th>
                    <th>Enquiry</th>
                    <th>Date</th>
                    <th>Delete</th>
                </tr>
                {% for e in enq %}
                    <tr>
                        <td>{{e.id}}</td>
                        <td>{{e.name}}</td>
                        <td>{{e.gender}}</td>
                        <td>{{e.address}}</td>
                         <td>{{e.contactno}}</td>
                         <td>{{e.emailaddress}}</td>
                         <td>{{e.enquirytext}}</td>
                         <td>{{e.enquirydate}}</td>
                         <td>
                             <a href="{% url 'adminzone:deleteenquiries' e.id %}">Delete</a>
                         </td>
                    </tr>
                {% endfor %}

            </table>
        </div>
        <div id="footer">
            <div id="lf"></div>
             <div id="rf"></div>
        </div>
        <div/>

</body>
</html>

adminzone/templates/knowledgebase.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>BLOGGING WEBSITE</title>

    <style>
#outer
{
min-height:950px;
width:1000px;
border:1px solid white;
margin:auto;
height:auto;
}
#header
{
height:150px;
width:1000px;
}#header
{
height:150px;
width:1000px;
}
#logo
{
height:150px;
width:150px;
background-color:cyan;
float:left;
}
#banner
{
height:150px;
width:850px;
background-color:teal;
float:right;
text-align:center;
line-height:150px;
}
#menu
{
width:1000px;
height:50px;
background-color:white;
margin-top:5px;
border:1px solid white;
}
#menu ul
{
 list-style-type:none;
}
#menu ul li
{
 display:inline;
}
#menu ul li a
{
 font-size:25px;
 padding:10px;
 text-decoration:none;
 color:black;
}
#menu ul li a:hover
{
 color:red;
}
#slider
{
width:1000px;
height:250px;
background-color:lightgrey;
margin-top:5px;

}
#parent
{
min-height:600px;
width:1000px;
margin-top:5px;
background-color:white;
height:auto;
}
#footer
{
width:1000px;
height:130px;
margin-top:5px
}
#lf
{
width:500px;
height:130px;
background-color:black;
color:white;
text-align:center;
float:right;
}
#rf
{
width:500px;
height:130px;
background-color:grey;
color:white;
text-align:center;
float:right;
}
</style>
<script>
    var images=["admin1.jpg" , "admin2", "knowledge1.jpg","knowledge2.jpg","knowledge3.jpg"];
   var i=0;
   baseUrl="{% static 'images/'%}";
   function moveslider()
   {
     if (i==5)
     {
      i=0;
     }
     document.getElementById("slide").src=baseUrl+images[i];
     i++;
     window.setTimeout("moveslider()",1000);
   }
</script>
</head>
<body bgcolor="blue" onload="moveslider()">
    <div id="outer">
        <div id="header">
            <div id="logo">
                <img src="{% static 'images/blogparent.jpg' %}" height="150px" width="150px"/>
            </div>
            <div id="banner">BLOGGING WEBSITE</div>
        </div>
        <div id="menu">
            <ul>
                <li><a href="{% url 'adminzone:adminhome' %}">Admin Home</a></li>
                <li><a href="{% url 'adminzone:enquiries' %}">Enquiries</a></li>
                <li><a href="{% url 'adminzone:complains' %}">Complains</a></li>
                <li><a href="{% url 'adminzone:customerinfo' %}">Customer Info</a></li>
                <li><a href="{% url 'adminzone:knowledgebase' %}">Knowledgebase</a></li>
                <li><a href="{% url 'adminzone:logout' %}">Logout</a></li>
            </ul>


        </div>
        <div id="slider">
            <img id="slide" width="1000" height="250"/>
        </div>

        <div id="parent">
            <form action="{% url 'adminzone:saveknowledgebase' %}" method="post">
                {% csrf_token %}
                <h2 style="text-align:center;color:blue;">
                    Knowledgebase Management
                </h2>
                <table border="1" style="margin:0 auto;width:50%;">
                    <tr>
                        <td>Enter problem id</td>
                        <td>
                        <input type="text" name="problemid" required/>
                        </td>
                    </tr>
                    <tr>
                        <td>Enter Problem Text</td>
                        <td>
                            <textarea name="problemtext" required style="height:100px;resize:none;"></textarea>
                        </td>
                    </tr>
                    <tr>
                        <td>Enter Solution Text</td>
                        <td>
                            <textarea name="solutiontext" required style="height:100px;resize:none;"></textarea>
                        </td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>
                            <input type="submit" value="save"/>
                        </td>
                    </tr>

                </table>
            </form>
        </div>
        <div id="footer">
            <div id="lf"></div>
             <div id="rf"></div>
        </div>
        <div/>

</body>
</html>

adminzone/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>